name: bento
on: [push]
jobs:
  bento:
    runs-on: ubuntu-latest
    name: check
    steps:
    - uses: actions/checkout@v1
    - name: bento check
      id: bento
      uses: returntocorp/bento-action@bence/refactor
      with:
        acceptTermsWithEmail: test@returntocorp.com
